control_freq: 5
control_mode: pd_ee_delta_pose_euler
device: cuda:0
eval_procs: 1
eval_steps:
- 2000000
gen_traj_mode: bezier2d
goal_aux: true
goal_thresh: 0.25
grasp_points_mode: gauss
grasp_select_mode: near4
info_exist_weight: 0.3
max_steps: 100
n_stack: 4
num_grasp_points: 20
num_grasps: 40
obj_init_rot: 0.0
obj_init_rot_z: true
obs_mode: state_egopoints
reward_mode: dense
robot_id: ur5e_robotiq85_old
robot_init_qpos_noise: 0.05
robot_x_offset: 0.56
seed: 1029
shader_dir: ibl
share_feat: false
sim_freq: 150
test_num: 20
total_timesteps: 300000
train_procs: 8
vary_speed: true
