control_freq: 5
control_mode: pd_ee_delta_pose_euler
device: cuda:0
eval_procs: 1
eval_steps:
- 2000000
gen_traj_mode: bezier2d
goal_aux: false
goal_thresh: 0.25
grasp_points_mode: gauss
grasp_select_mode: near4
log_dir: 20260629_173435_sac4_state_egopoints_pd_ee_delta_pose_euler_YCB12_40_bezier2d_vary_None
max_steps: 100
num_grasp_points: 20
num_grasps: 40
obj_init_rot: 0.0
obj_init_rot_z: true
obs_mode: state_egopoints
reward_mode: dense
robot_id: ur5e_robotiq85_old
robot_init_qpos_noise: 0.05
robot_x_offset: 0.56
shader_dir: ibl
share_feat: true
sim_freq: 150
test_num: 20
train_procs: 4
vary_speed: true
